#!/bin/bash

templates=$(python -c 'import glob; print([f.replace("micromlgen/", "") for f in glob.glob("micromlgen/templates/**/*", recursive=True).append(glob.glob("micromlgen/templates_C/**/*", recursive=True))])')
templates=$(printf '%s\n' "$templates" | sed -e 's/[\/&]/\\&/g')
rm dist/micromlgen-${1}.tar.gz
cp setup_template.py setup.py
sed -i "" "s/PACKAGE_DATA/$templates/" setup.py
sed -i "" "s/VERSION/${1}/" setup.py
python setup.py sdist
twine upload -u eloquentarduino dist/micromlgen-${1}.tar.gz
git add .
git commit -m "bump dist to ${1}"
git push origin master -f