#!/bin/bash

rm dist/micromlgen-${1}.tar.gz
cp setup_template.py setup.py
sed -i "s/VERSION/${1}/g" setup.py
python setup.py sdist
twine upload dist/*
rm dist/micromlgen-${1}.tar.gz
# tar -czv -f dist/micromlgen-${1}.tar.gz micromlgen --exclude='*.pyc'
git add .
git commit -m "bump dist to ${1}"
git push origin master -f